[target.riscv64imac-unknown-none-elf]
linker = "rust-lld"
rustflags = [
  "-Crelocation-model=pic",
  "-Clink-arg=--pie",
  "-Clink-arg=--pic-veneer",
  "-Clink-arg=-Bstatic",
  "-Clink-arg=--apply-dynamic-relocs",
  "-Clink-arg=--ignore-function-address-equality",
  "-Clink-arg=--ignore-data-address-equality",
  "-Clink-arg=-zseparate-loadable-segments",
  "-Clink-arg=--pack-dyn-relocs=relr",
  "-Ztls-model=local-exec",
]

[profile.dev]
incremental = true
# lto = 'thin'
# opt-level = 1

[profile.release]
lto = 'fat'
opt-level = 3
