[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mizu"
version = "0.1.0"

[features]
default = ["qemu-virt"]
qemu-virt = ["config/qemu-virt"]

[dependencies]
# Local crates
co-trap = {path = "../lib/co-trap"}
config = {path = "../lib/config", default-features = false}
klog = {path = "../lib/klog"}
ksync = {path = "../lib/ksync"}
rv39-paging = {path = "../lib/paging"}
# External crates
r0 = "1"
riscv = "0"
sbi-rt = {git = "https://github.com/js2xxx/sbi-rt", branch = "multitarget"}

[build-dependencies]
config = {path = "../lib/config", default-features = false}
