[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/js2xxx/arsc"]
git = "https://github.com/js2xxx/arsc"
replace-with = "vendored-sources"

[source."git+https://github.com/js2xxx/event-listener"]
git = "https://github.com/js2xxx/event-listener"
replace-with = "vendored-sources"

[source."git+https://github.com/js2xxx/sbi-rt?branch=multitarget"]
git = "https://github.com/js2xxx/sbi-rt"
branch = "multitarget"
replace-with = "vendored-sources"

[source."git+https://github.com/js2xxx/scoped-tls?branch=no_std"]
git = "https://github.com/js2xxx/scoped-tls"
branch = "no_std"
replace-with = "vendored-sources"

[source."git+https://github.com/js2xxx/smoltcp?branch=reuse_endpoints"]
git = "https://github.com/js2xxx/smoltcp"
branch = "reuse_endpoints"
replace-with = "vendored-sources"

[source."git+https://github.com/rcore-os/virtio-drivers?branch=new-netdev"]
git = "https://github.com/rcore-os/virtio-drivers"
branch = "new-netdev"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "third-party/vendor"
[profile.dev]
incremental = true

[profile.release]
lto = true

[build]
rustflags = ["-Zshare-generics=n"]
