name: "Code check"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Check clippy
        run: cargo clippy --target riscv64imac-unknown-none-elf

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check format
        run: cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools

      - name: Install other dependencies
        run: |
          sudo apt install make
          cargo install cargo-binutils

      - name: Build
        run: make build

      - name: Build release
        run: make build MODE=release

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools

      - name: Install other dependencies
        run: |
          sudo apt install make
          cargo install cargo-binutils

      - name: Test
        run: make test
