on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Push Mirror
      env:
        SRC: 'https://github.com/js2xxx/umi.git'
        DST: 'https://gitlab.eduxiji.net/PLNTRY/OSKernel2023-umi.git'
      run: |
        git clone --mirror "$SRC" && cd `basename "$SRC" .git`
        git remote set-url --push origin "$DST"
        git fetch -p origin
        git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
        git push --mirror
