name: "Mirror to Gitlab"

on:
  push:
    branches: ["master"]
  pull_request_target:
    branches: ["master"]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo All PR should be approved first to prevent any malicious code to be mirrored to the destination.

  deploy:
    runs-on: ubuntu-latest
    needs: [approve]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deployed
          fetch-depth: 0

      - name: Rebase on master
        run: git rebase master

      - name: Revendor dependencies
        run: sh scripts/revendor.sh

      - name: Test build
        run: make all

      - name: Deploy to the branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Deployment"
          git push

  mirror:
    runs-on: ubuntu-latest
    needs: [approve, deploy]
    environment:
      name: Integrate Pull Request
    env:
      SRC: "https://github.com/js2xxx/umi.git"
      DST: "https://PLNTRY:${{ secrets.PASSWORD }}@gitlab.eduxiji.net/PLNTRY/OSKernel2023-umi.git"
    steps:
      - name: Clone the source
        run: git clone --mirror "$SRC"

      - name: Set remote
        run: cd `basename "$SRC"` && git remote set-url --push origin "$DST"

      - name: Fetch remote
        run: cd `basename "$SRC"` && git fetch -p origin

      - name: Update branches
        run: cd `basename "$SRC"` && git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin

      - name: Push to the destination
        run: cd `basename "$SRC"` && git push --mirror
